import './globals.css'
import Link from 'next/link'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header className="w-full mb-10">
          <ul className="flex justify-between bg-blue-500 w-full py-4 px-16">
            <li className="flex-1 text-white uppercase text-2xl">
              <Link href={"/"}>CCEAK Books</Link>
            </li>
            <li className="text-white uppercase hover:underline text-xl mr-10">
              <Link href={"/pages/all-books"}>Todos os Livros</Link>
            </li>
            <li className="text-white uppercase hover:underline text-xl">
              <Link href={"/pages/book-registration"}>Cadastrar Livro</Link>
            </li>
          </ul>
        </header>
        {children}
      </body>
    </html>
  )
}
